package tkyjovsk.sorting.visual;

import javax.swing.JFrame;
import tkyjovsk.sorting.Item;
import static tkyjovsk.sorting.Item.AGE;
import static tkyjovsk.sorting.Item.NAME;
import tkyjovsk.sorting.ItemComparator;
import tkyjovsk.sorting.ItemTreeSet;
import tkyjovsk.sorting.SortKey;
import static tkyjovsk.sorting.Item.RANK;

/**
 *
 * @author tkyjovsk
 */
public class TablePanel extends javax.swing.JPanel {

  /**
   * Creates new form NewJPanel
   */
  public TablePanel() {
    initComponents();
  }

  public static void main(String[] args) {

    ItemTreeSet items = new ItemTreeSet(new ItemComparator().clear().add(new SortKey(AGE, false)));;

    Item alice = new Item().set(NAME, "Alice").set(AGE, "25").set(RANK, "English");
    Item bob = new Item().set(NAME, "Bob").set(AGE, "20").set(RANK, "Danish");
    Item carol = new Item().set(NAME, "Carol").set(AGE, "30").set(RANK, "Canadian");
    Item david = new Item().set(NAME, "David").set(RANK, "Brazilian");
    Item eve = new Item().set(NAME, "Eve").set(AGE, "30").set(RANK, "Armenian");

    alice = new Item().set(NAME, "Alice").set(AGE, "25");
    bob = new Item().set(NAME, "Bob").set(AGE, "20");
    carol = new Item().set(NAME, "Carol").set(AGE, "30");
    david = new Item().set(NAME, "David");
    eve = new Item().set(NAME, "Eve").set(AGE, "30");

    JFrame f = new JFrame();
    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    f.setSize(720, 480);
    f.setLocation(200, 200);
    f.add(new TablePanel());
    f.setVisible(true);

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Title 1", "Title 2", "Title 3"
      }
    ));
    jScrollPane1.setViewportView(jTable1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
